steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "europe-west3-docker.pkg.dev/$PROJECT_ID/$_SERVICE_NAME:$BRANCH_NAME", "-f", "/Dockerfile", ".", "--build-arg", "PORT=8080"]
substitutions:
  _SERVICE_NAME: test
images:
  - "europe-west3-docker.pkg.dev/$PROJECT_ID/$_SERVICE_NAME:$BRANCH_NAME"
timeout: 1200s    